name: 'Obsidian-Zola Build for Pages'
description: 'Build an obsidian-zola site, and push it to gh-pages branch'
author: 'Trent Walraven'
runs:
  using: "composite"
  steps: 
    - run: sudo apt-get update && sudo apt-get install -yqq wget git python-is-python3 python3-pip rsync    
      shell: bash
      
    - run: sudo pip3 install python-slugify rtoml
      shell: bash
      
    - run: sudo wget -q -O - "https://github.com/getzola/zola/releases/download/v0.15.2/zola-v0.15.2-x86_64-unknown-linux-gnu.tar.gz" | sudo tar xzf - -C /usr/local/bin
      shell: bash
      
    - run: sudo /bin/bash -C "$(curl -fSSL https://raw.githubusercontent.com/hackedXD/obsidian-zola-build-action/main/entrypoint.sh)"
      shell: bash
    
branding:
  icon: 'moon'  
  color: 'blue'
